package main

import (
	"log"
	"net/http"

	"github.com/nombiezinja/yeet-fb/internal/config"
	"github.com/nombiezinja/yeet-fb/internal/router"
	"github.com/nombiezinja/yeet-fb/service"
)

func main() {
	cfg, err := config.New()
	if err != nil {
		log.Fatal(err)
	}

	// Initialize new mux with middlewares
	r := router.NewRouter(cfg)

	// Initialize server with handlers generated by oapi-codegen
	s, _ := service.New(cfg, r)

	logger := cfg.Logger
	logger.Info("Serving application at port " + cfg.ConfigVars.Port)

	err = http.ListenAndServe(":"+cfg.ConfigVars.Port, *s.Handler)
	if err != nil {
		logger.Error(err.Error())
	}
}
