// Package generatedserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package generatedserver

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for BatchDeleteResponseResultsStatus.
const (
	BatchDeleteResponseResultsStatusFailed      BatchDeleteResponseResultsStatus = "failed"
	BatchDeleteResponseResultsStatusQueued      BatchDeleteResponseResultsStatus = "queued"
	BatchDeleteResponseResultsStatusRateLimited BatchDeleteResponseResultsStatus = "rate_limited"
	BatchDeleteResponseResultsStatusSuccess     BatchDeleteResponseResultsStatus = "success"
)

// Defines values for BatchDeleteResponseStatus.
const (
	BatchDeleteResponseStatusCancelled  BatchDeleteResponseStatus = "cancelled"
	BatchDeleteResponseStatusCompleted  BatchDeleteResponseStatus = "completed"
	BatchDeleteResponseStatusFailed     BatchDeleteResponseStatus = "failed"
	BatchDeleteResponseStatusInProgress BatchDeleteResponseStatus = "in_progress"
	BatchDeleteResponseStatusQueued     BatchDeleteResponseStatus = "queued"
)

// Defines values for BulkDeleteResponseStatus.
const (
	Cancelled  BulkDeleteResponseStatus = "cancelled"
	Completed  BulkDeleteResponseStatus = "completed"
	Failed     BulkDeleteResponseStatus = "failed"
	InProgress BulkDeleteResponseStatus = "in_progress"
	Queued     BulkDeleteResponseStatus = "queued"
)

// Defines values for HealthResponseDependenciesStatus.
const (
	HealthResponseDependenciesStatusHealthy   HealthResponseDependenciesStatus = "healthy"
	HealthResponseDependenciesStatusUnhealthy HealthResponseDependenciesStatus = "unhealthy"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded  HealthResponseStatus = "degraded"
	HealthResponseStatusHealthy   HealthResponseStatus = "healthy"
	HealthResponseStatusUnhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for PostPrivacyValue.
const (
	ALLFRIENDS       PostPrivacyValue = "ALL_FRIENDS"
	CUSTOM           PostPrivacyValue = "CUSTOM"
	EVERYONE         PostPrivacyValue = "EVERYONE"
	FRIENDSOFFRIENDS PostPrivacyValue = "FRIENDS_OF_FRIENDS"
	SELF             PostPrivacyValue = "SELF"
)

// Defines values for PostType.
const (
	PostTypeEvent  PostType = "event"
	PostTypeLink   PostType = "link"
	PostTypeNote   PostType = "note"
	PostTypePhoto  PostType = "photo"
	PostTypeStatus PostType = "status"
	PostTypeVideo  PostType = "video"
)

// Defines values for PrincipalStatus.
const (
	Active      PrincipalStatus = "active"
	Deactivated PrincipalStatus = "deactivated"
	Suspended   PrincipalStatus = "suspended"
)

// Defines values for PrincipalType.
const (
	Admin   PrincipalType = "admin"
	Service PrincipalType = "service"
	User    PrincipalType = "user"
)

// Defines values for DeleteAllPostsParamsConfirm.
const (
	DELETEALLPOSTS DeleteAllPostsParamsConfirm = "DELETE_ALL_POSTS"
)

// Defines values for ListPostsParamsType.
const (
	ListPostsParamsTypeEvent  ListPostsParamsType = "event"
	ListPostsParamsTypeLink   ListPostsParamsType = "link"
	ListPostsParamsTypePhoto  ListPostsParamsType = "photo"
	ListPostsParamsTypeStatus ListPostsParamsType = "status"
	ListPostsParamsTypeVideo  ListPostsParamsType = "video"
)

// BatchDeleteRequest defines model for BatchDeleteRequest.
type BatchDeleteRequest struct {
	// DryRun Preview without executing
	DryRun *bool `json:"dry_run,omitempty"`

	// PostIds Facebook post IDs to delete
	PostIds []string `json:"post_ids"`
}

// BatchDeleteResponse defines model for BatchDeleteResponse.
type BatchDeleteResponse struct {
	// DeletedPosts Successfully deleted posts
	DeletedPosts        *int       `json:"deleted_posts,omitempty"`
	EstimatedCompletion *time.Time `json:"estimated_completion,omitempty"`

	// FailedPosts Failed deletion attempts
	FailedPosts *int `json:"failed_posts,omitempty"`

	// OperationId Unique operation identifier
	OperationId openapi_types.UUID `json:"operation_id"`

	// ProcessedPosts Posts already processed
	ProcessedPosts *int `json:"processed_posts,omitempty"`
	RateLimitInfo  *struct {
		CurrentUsage    *int       `json:"current_usage,omitempty"`
		RequestsPerHour *int       `json:"requests_per_hour,omitempty"`
		ResetTime       *time.Time `json:"reset_time,omitempty"`
	} `json:"rate_limit_info,omitempty"`
	Results *[]struct {
		Error  *string                           `json:"error,omitempty"`
		PostId *string                           `json:"post_id,omitempty"`
		Status *BatchDeleteResponseResultsStatus `json:"status,omitempty"`
	} `json:"results,omitempty"`
	Status BatchDeleteResponseStatus `json:"status"`

	// TotalPosts Total posts to process
	TotalPosts *int `json:"total_posts,omitempty"`
}

// BatchDeleteResponseResultsStatus defines model for BatchDeleteResponse.Results.Status.
type BatchDeleteResponseResultsStatus string

// BatchDeleteResponseStatus defines model for BatchDeleteResponse.Status.
type BatchDeleteResponseStatus string

// BulkDeleteResponse defines model for BulkDeleteResponse.
type BulkDeleteResponse struct {
	// DeletedPosts Successfully deleted posts
	DeletedPosts        *int       `json:"deleted_posts,omitempty"`
	EstimatedCompletion *time.Time `json:"estimated_completion,omitempty"`

	// FailedPosts Failed deletion attempts
	FailedPosts *int `json:"failed_posts,omitempty"`

	// OperationId Unique operation identifier
	OperationId openapi_types.UUID `json:"operation_id"`

	// ProcessedPosts Posts already processed
	ProcessedPosts *int `json:"processed_posts,omitempty"`
	RateLimitInfo  *struct {
		CurrentUsage    *int       `json:"current_usage,omitempty"`
		RequestsPerHour *int       `json:"requests_per_hour,omitempty"`
		ResetTime       *time.Time `json:"reset_time,omitempty"`
	} `json:"rate_limit_info,omitempty"`
	Status BulkDeleteResponseStatus `json:"status"`

	// TotalPosts Total posts to process
	TotalPosts *int `json:"total_posts,omitempty"`
}

// BulkDeleteResponseStatus defines model for BulkDeleteResponse.Status.
type BulkDeleteResponseStatus string

// CreatePrincipalRequest defines model for CreatePrincipalRequest.
type CreatePrincipalRequest struct {
	Email     openapi_types.Email `json:"email"`
	FirstName *string             `json:"first_name,omitempty"`
	LastName  *string             `json:"last_name,omitempty"`

	// PrincipalType Principal classification
	PrincipalType PrincipalType `json:"principal_type"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Machine-readable error code
		Code string `json:"code"`

		// Details Additional error context
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Human-readable error message
		Message string `json:"message"`

		// RequestId Unique request identifier for debugging
		RequestId *string `json:"request_id,omitempty"`
	} `json:"error"`
}

// FacebookAuthUrlResponse defines model for FacebookAuthUrlResponse.
type FacebookAuthUrlResponse struct {
	// AuthorizationUrl Facebook OAuth authorization URL
	AuthorizationUrl string `json:"authorization_url"`

	// ExpiresIn State validity in seconds
	ExpiresIn *int `json:"expires_in,omitempty"`

	// State CSRF protection state parameter
	State string `json:"state"`
}

// FacebookCallbackRequest defines model for FacebookCallbackRequest.
type FacebookCallbackRequest struct {
	// Code Authorization code from Facebook
	Code string `json:"code"`

	// Error Error code if authorization denied
	Error *string `json:"error,omitempty"`

	// ErrorDescription Human-readable error description
	ErrorDescription *string `json:"error_description,omitempty"`

	// State CSRF state parameter
	State string `json:"state"`
}

// FacebookError defines model for FacebookError.
type FacebookError struct {
	// Code Facebook error code
	Code *int `json:"code,omitempty"`

	// FbtraceId Facebook trace ID for debugging
	FbtraceId *string `json:"fbtrace_id,omitempty"`

	// Message Error message
	Message *string `json:"message,omitempty"`

	// Subcode Facebook error subcode
	Subcode *int `json:"subcode,omitempty"`

	// Type Error type
	Type *string `json:"type,omitempty"`
}

// FacebookTokenResponse defines model for FacebookTokenResponse.
type FacebookTokenResponse struct {
	// AccessToken Facebook access token (encrypted in storage)
	AccessToken string `json:"access_token"`

	// ExpiresIn Token lifetime in seconds
	ExpiresIn int `json:"expires_in"`

	// Scope Granted permissions
	Scope     *string `json:"scope,omitempty"`
	TokenType string  `json:"token_type"`

	// UserId Facebook user ID
	UserId *string `json:"user_id,omitempty"`

	// UserName Facebook user name
	UserName *string `json:"user_name,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Dependencies *map[string]struct {
		LatencyMs *float32                          `json:"latency_ms,omitempty"`
		Status    *HealthResponseDependenciesStatus `json:"status,omitempty"`
	} `json:"dependencies,omitempty"`
	Status    HealthResponseStatus `json:"status"`
	Timestamp time.Time            `json:"timestamp"`
	Uptime    *string              `json:"uptime,omitempty"`
	Version   *string              `json:"version,omitempty"`
}

// HealthResponseDependenciesStatus defines model for HealthResponse.Dependencies.Status.
type HealthResponseDependenciesStatus string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// AccessToken JWT access token
	AccessToken string `json:"access_token"`

	// ExpiresIn Token lifetime in seconds
	ExpiresIn *int `json:"expires_in,omitempty"`

	// FacebookConnected Whether Facebook account is linked
	FacebookConnected *bool              `json:"facebook_connected,omitempty"`
	PrincipalId       openapi_types.UUID `json:"principal_id"`
	TokenType         string             `json:"token_type"`
}

// Post defines model for Post.
type Post struct {
	Caption     *string   `json:"caption,omitempty"`
	CreatedTime time.Time `json:"created_time"`
	Description *string   `json:"description,omitempty"`

	// Id Facebook post ID
	Id          string  `json:"id"`
	IsPublished *bool   `json:"is_published,omitempty"`
	Link        *string `json:"link,omitempty"`

	// Message Post text content
	Message      *string `json:"message,omitempty"`
	Name         *string `json:"name,omitempty"`
	PermalinkUrl *string `json:"permalink_url,omitempty"`
	Picture      *string `json:"picture,omitempty"`
	Privacy      *struct {
		Value *PostPrivacyValue `json:"value,omitempty"`
	} `json:"privacy,omitempty"`
	Reactions *struct {
		Summary *struct {
			TotalCount *int `json:"total_count,omitempty"`
		} `json:"summary,omitempty"`
	} `json:"reactions,omitempty"`
	Shares *struct {
		Count *int `json:"count,omitempty"`
	} `json:"shares,omitempty"`
	Source     *string `json:"source,omitempty"`
	StatusType *string `json:"status_type,omitempty"`

	// Story Auto-generated story text
	Story       *string    `json:"story,omitempty"`
	Type        *PostType  `json:"type,omitempty"`
	UpdatedTime *time.Time `json:"updated_time,omitempty"`
}

// PostPrivacyValue defines model for Post.Privacy.Value.
type PostPrivacyValue string

// PostType defines model for Post.Type.
type PostType string

// PostDetailResponse defines model for PostDetailResponse.
type PostDetailResponse struct {
	// CachedAt When this data was last fetched from Facebook
	CachedAt *time.Time `json:"cached_at,omitempty"`
	Post     Post       `json:"post"`
}

// PostsListResponse defines model for PostsListResponse.
type PostsListResponse struct {
	HasMore       *bool   `json:"has_more,omitempty"`
	NextPageToken *string `json:"next_page_token,omitempty"`
	Posts         []Post  `json:"posts"`
	TotalCount    *int    `json:"total_count,omitempty"`
}

// Principal defines model for Principal.
type Principal struct {
	CreatedAt           time.Time           `json:"created_at"`
	Email               openapi_types.Email `json:"email"`
	FacebookConnectedAt *time.Time          `json:"facebook_connected_at,omitempty"`

	// FacebookUserId Linked Facebook user ID
	FacebookUserId *string            `json:"facebook_user_id,omitempty"`
	FirstName      *string            `json:"first_name,omitempty"`
	Id             openapi_types.UUID `json:"id"`
	LastLoginAt    *time.Time         `json:"last_login_at,omitempty"`
	LastName       *string            `json:"last_name,omitempty"`

	// PrincipalType Principal classification
	PrincipalType PrincipalType `json:"principal_type"`

	// Status Principal account status
	Status    *PrincipalStatus `json:"status,omitempty"`
	UpdatedAt *time.Time       `json:"updated_at,omitempty"`
}

// PrincipalStatus Principal account status
type PrincipalStatus string

// PrincipalType Principal classification
type PrincipalType string

// PrincipalsListResponse defines model for PrincipalsListResponse.
type PrincipalsListResponse struct {
	NextPageToken *string     `json:"next_page_token,omitempty"`
	Principals    []Principal `json:"principals"`
	TotalCount    *int        `json:"total_count,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email           openapi_types.Email `json:"email"`
	FirstName       *string             `json:"first_name,omitempty"`
	InvitationToken string              `json:"invitation_token"`
	LastName        *string             `json:"last_name,omitempty"`

	// Password Must contain uppercase, lowercase, number, and special character
	Password string `json:"password"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	CreatedAt            time.Time           `json:"created_at"`
	Email                openapi_types.Email `json:"email"`
	PrincipalId          openapi_types.UUID  `json:"principal_id"`
	RequiresFacebookAuth *bool               `json:"requires_facebook_auth,omitempty"`
}

// TokenRefreshRequest defines model for TokenRefreshRequest.
type TokenRefreshRequest struct {
	// AccessToken Short-lived token to exchange
	AccessToken string `json:"access_token"`
}

// TokenVerifyRequest defines model for TokenVerifyRequest.
type TokenVerifyRequest struct {
	AccessToken string `json:"access_token"`
}

// TokenVerifyResponse defines model for TokenVerifyResponse.
type TokenVerifyResponse struct {
	AppId     *string        `json:"app_id,omitempty"`
	Error     *FacebookError `json:"error,omitempty"`
	ExpiresAt *time.Time     `json:"expires_at,omitempty"`
	IsValid   bool           `json:"is_valid"`
	Scopes    *[]string      `json:"scopes,omitempty"`
	UserId    *string        `json:"user_id,omitempty"`
}

// UpdatePrincipalRequest defines model for UpdatePrincipalRequest.
type UpdatePrincipalRequest struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName  *string `json:"last_name,omitempty"`

	// Status Principal account status
	Status *PrincipalStatus `json:"status,omitempty"`
}

// PageSize defines model for PageSize.
type PageSize = int

// PageToken defines model for PageToken.
type PageToken = string

// PostId defines model for PostId.
type PostId = string

// PrincipalId defines model for PrincipalId.
type PrincipalId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// GetFacebookAuthUrlParams defines parameters for GetFacebookAuthUrl.
type GetFacebookAuthUrlParams struct {
	// RedirectUri Callback URI (must be pre-registered)
	RedirectUri *string `form:"redirect_uri,omitempty" json:"redirect_uri,omitempty"`

	// Scope Requested Facebook permissions
	Scope *string `form:"scope,omitempty" json:"scope,omitempty"`
}

// ListPrincipalsParams defines parameters for ListPrincipals.
type ListPrincipalsParams struct {
	// PageSize Number of items per page (max 100)
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Pagination token for next page
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// DeleteAllPostsParams defines parameters for DeleteAllPosts.
type DeleteAllPostsParams struct {
	// Confirm Confirmation flag (must be 'DELETE_ALL_POSTS')
	Confirm DeleteAllPostsParamsConfirm `form:"confirm" json:"confirm"`

	// DryRun Preview deletion without executing
	DryRun *bool `form:"dry_run,omitempty" json:"dry_run,omitempty"`
}

// DeleteAllPostsParamsConfirm defines parameters for DeleteAllPosts.
type DeleteAllPostsParamsConfirm string

// ListPostsParams defines parameters for ListPosts.
type ListPostsParams struct {
	// PageSize Number of items per page (max 100)
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Pagination token for next page
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`

	// Type Filter by post type
	Type *ListPostsParamsType `form:"type,omitempty" json:"type,omitempty"`

	// CreatedSince Filter posts created after this date
	CreatedSince *time.Time `form:"created_since,omitempty" json:"created_since,omitempty"`

	// CreatedUntil Filter posts created before this date
	CreatedUntil *time.Time `form:"created_until,omitempty" json:"created_until,omitempty"`
}

// ListPostsParamsType defines parameters for ListPosts.
type ListPostsParamsType string

// HandleFacebookCallbackJSONRequestBody defines body for HandleFacebookCallback for application/json ContentType.
type HandleFacebookCallbackJSONRequestBody = FacebookCallbackRequest

// RefreshFacebookTokenJSONRequestBody defines body for RefreshFacebookToken for application/json ContentType.
type RefreshFacebookTokenJSONRequestBody = TokenRefreshRequest

// VerifyFacebookTokenJSONRequestBody defines body for VerifyFacebookToken for application/json ContentType.
type VerifyFacebookTokenJSONRequestBody = TokenVerifyRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreatePrincipalJSONRequestBody defines body for CreatePrincipal for application/json ContentType.
type CreatePrincipalJSONRequestBody = CreatePrincipalRequest

// UpdatePrincipalJSONRequestBody defines body for UpdatePrincipal for application/json ContentType.
type UpdatePrincipalJSONRequestBody = UpdatePrincipalRequest

// BatchDeletePostsJSONRequestBody defines body for BatchDeletePosts for application/json ContentType.
type BatchDeletePostsJSONRequestBody = BatchDeleteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Facebook OAuth authorization URL
	// (GET /auth/facebook/authorize)
	GetFacebookAuthUrl(w http.ResponseWriter, r *http.Request, params GetFacebookAuthUrlParams)
	// Process Facebook OAuth callback
	// (POST /auth/facebook/callback)
	HandleFacebookCallback(w http.ResponseWriter, r *http.Request)
	// Exchange short-lived for long-lived token
	// (POST /auth/facebook/token/refresh)
	RefreshFacebookToken(w http.ResponseWriter, r *http.Request)
	// Verify Facebook access token validity
	// (POST /auth/facebook/token/verify)
	VerifyFacebookToken(w http.ResponseWriter, r *http.Request)
	// Authenticate user credentials
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout and invalidate tokens
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Register new user with invite code
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)

	// (GET /favicon.ico)
	GetFavicon(w http.ResponseWriter, r *http.Request)
	// Health check endpoint
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// List system principals
	// (GET /principals)
	ListPrincipals(w http.ResponseWriter, r *http.Request, params ListPrincipalsParams)
	// Create new principal
	// (POST /principals)
	CreatePrincipal(w http.ResponseWriter, r *http.Request)
	// Delete principal
	// (DELETE /principals/{principal_id})
	DeletePrincipal(w http.ResponseWriter, r *http.Request, principalId PrincipalId)
	// Get principal details
	// (GET /principals/{principal_id})
	GetPrincipal(w http.ResponseWriter, r *http.Request, principalId PrincipalId)
	// Update principal
	// (PUT /principals/{principal_id})
	UpdatePrincipal(w http.ResponseWriter, r *http.Request, principalId PrincipalId)
	// Delete all posts
	// (DELETE /principals/{principal_id}/posts)
	DeleteAllPosts(w http.ResponseWriter, r *http.Request, principalId PrincipalId, params DeleteAllPostsParams)
	// List Facebook posts
	// (GET /principals/{principal_id}/posts)
	ListPosts(w http.ResponseWriter, r *http.Request, principalId PrincipalId, params ListPostsParams)
	// Delete specific post
	// (DELETE /principals/{principal_id}/posts/{post_id})
	DeletePost(w http.ResponseWriter, r *http.Request, principalId PrincipalId, postId PostId)
	// Get specific post
	// (GET /principals/{principal_id}/posts/{post_id})
	GetPost(w http.ResponseWriter, r *http.Request, principalId PrincipalId, postId PostId)
	// Batch delete specific posts
	// (POST /principals/{principal_id}/posts:batchDelete)
	BatchDeletePosts(w http.ResponseWriter, r *http.Request, principalId PrincipalId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get Facebook OAuth authorization URL
// (GET /auth/facebook/authorize)
func (_ Unimplemented) GetFacebookAuthUrl(w http.ResponseWriter, r *http.Request, params GetFacebookAuthUrlParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Process Facebook OAuth callback
// (POST /auth/facebook/callback)
func (_ Unimplemented) HandleFacebookCallback(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Exchange short-lived for long-lived token
// (POST /auth/facebook/token/refresh)
func (_ Unimplemented) RefreshFacebookToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify Facebook access token validity
// (POST /auth/facebook/token/verify)
func (_ Unimplemented) VerifyFacebookToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Authenticate user credentials
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout and invalidate tokens
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register new user with invite code
// (POST /auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /favicon.ico)
func (_ Unimplemented) GetFavicon(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check endpoint
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List system principals
// (GET /principals)
func (_ Unimplemented) ListPrincipals(w http.ResponseWriter, r *http.Request, params ListPrincipalsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create new principal
// (POST /principals)
func (_ Unimplemented) CreatePrincipal(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete principal
// (DELETE /principals/{principal_id})
func (_ Unimplemented) DeletePrincipal(w http.ResponseWriter, r *http.Request, principalId PrincipalId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get principal details
// (GET /principals/{principal_id})
func (_ Unimplemented) GetPrincipal(w http.ResponseWriter, r *http.Request, principalId PrincipalId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update principal
// (PUT /principals/{principal_id})
func (_ Unimplemented) UpdatePrincipal(w http.ResponseWriter, r *http.Request, principalId PrincipalId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete all posts
// (DELETE /principals/{principal_id}/posts)
func (_ Unimplemented) DeleteAllPosts(w http.ResponseWriter, r *http.Request, principalId PrincipalId, params DeleteAllPostsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Facebook posts
// (GET /principals/{principal_id}/posts)
func (_ Unimplemented) ListPosts(w http.ResponseWriter, r *http.Request, principalId PrincipalId, params ListPostsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete specific post
// (DELETE /principals/{principal_id}/posts/{post_id})
func (_ Unimplemented) DeletePost(w http.ResponseWriter, r *http.Request, principalId PrincipalId, postId PostId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get specific post
// (GET /principals/{principal_id}/posts/{post_id})
func (_ Unimplemented) GetPost(w http.ResponseWriter, r *http.Request, principalId PrincipalId, postId PostId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Batch delete specific posts
// (POST /principals/{principal_id}/posts:batchDelete)
func (_ Unimplemented) BatchDeletePosts(w http.ResponseWriter, r *http.Request, principalId PrincipalId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetFacebookAuthUrl operation middleware
func (siw *ServerInterfaceWrapper) GetFacebookAuthUrl(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFacebookAuthUrlParams

	// ------------- Optional query parameter "redirect_uri" -------------

	err = runtime.BindQueryParameter("form", true, false, "redirect_uri", r.URL.Query(), &params.RedirectUri)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_uri", Err: err})
		return
	}

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFacebookAuthUrl(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleFacebookCallback operation middleware
func (siw *ServerInterfaceWrapper) HandleFacebookCallback(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleFacebookCallback(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshFacebookToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshFacebookToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshFacebookToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyFacebookToken operation middleware
func (siw *ServerInterfaceWrapper) VerifyFacebookToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyFacebookToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFavicon operation middleware
func (siw *ServerInterfaceWrapper) GetFavicon(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFavicon(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPrincipals operation middleware
func (siw *ServerInterfaceWrapper) ListPrincipals(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPrincipalsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPrincipals(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePrincipal operation middleware
func (siw *ServerInterfaceWrapper) CreatePrincipal(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePrincipal(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePrincipal operation middleware
func (siw *ServerInterfaceWrapper) DeletePrincipal(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "principal_id" -------------
	var principalId PrincipalId

	err = runtime.BindStyledParameterWithOptions("simple", "principal_id", chi.URLParam(r, "principal_id"), &principalId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "principal_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePrincipal(w, r, principalId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPrincipal operation middleware
func (siw *ServerInterfaceWrapper) GetPrincipal(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "principal_id" -------------
	var principalId PrincipalId

	err = runtime.BindStyledParameterWithOptions("simple", "principal_id", chi.URLParam(r, "principal_id"), &principalId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "principal_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPrincipal(w, r, principalId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePrincipal operation middleware
func (siw *ServerInterfaceWrapper) UpdatePrincipal(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "principal_id" -------------
	var principalId PrincipalId

	err = runtime.BindStyledParameterWithOptions("simple", "principal_id", chi.URLParam(r, "principal_id"), &principalId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "principal_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePrincipal(w, r, principalId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAllPosts operation middleware
func (siw *ServerInterfaceWrapper) DeleteAllPosts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "principal_id" -------------
	var principalId PrincipalId

	err = runtime.BindStyledParameterWithOptions("simple", "principal_id", chi.URLParam(r, "principal_id"), &principalId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "principal_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteAllPostsParams

	// ------------- Required query parameter "confirm" -------------

	if paramValue := r.URL.Query().Get("confirm"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "confirm"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "confirm", r.URL.Query(), &params.Confirm)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "confirm", Err: err})
		return
	}

	// ------------- Optional query parameter "dry_run" -------------

	err = runtime.BindQueryParameter("form", true, false, "dry_run", r.URL.Query(), &params.DryRun)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dry_run", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAllPosts(w, r, principalId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPosts operation middleware
func (siw *ServerInterfaceWrapper) ListPosts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "principal_id" -------------
	var principalId PrincipalId

	err = runtime.BindStyledParameterWithOptions("simple", "principal_id", chi.URLParam(r, "principal_id"), &principalId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "principal_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPostsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "created_since" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_since", r.URL.Query(), &params.CreatedSince)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_since", Err: err})
		return
	}

	// ------------- Optional query parameter "created_until" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_until", r.URL.Query(), &params.CreatedUntil)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_until", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPosts(w, r, principalId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePost operation middleware
func (siw *ServerInterfaceWrapper) DeletePost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "principal_id" -------------
	var principalId PrincipalId

	err = runtime.BindStyledParameterWithOptions("simple", "principal_id", chi.URLParam(r, "principal_id"), &principalId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "principal_id", Err: err})
		return
	}

	// ------------- Path parameter "post_id" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePost(w, r, principalId, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPost operation middleware
func (siw *ServerInterfaceWrapper) GetPost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "principal_id" -------------
	var principalId PrincipalId

	err = runtime.BindStyledParameterWithOptions("simple", "principal_id", chi.URLParam(r, "principal_id"), &principalId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "principal_id", Err: err})
		return
	}

	// ------------- Path parameter "post_id" -------------
	var postId PostId

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPost(w, r, principalId, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BatchDeletePosts operation middleware
func (siw *ServerInterfaceWrapper) BatchDeletePosts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "principal_id" -------------
	var principalId PrincipalId

	err = runtime.BindStyledParameterWithOptions("simple", "principal_id", chi.URLParam(r, "principal_id"), &principalId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "principal_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BatchDeletePosts(w, r, principalId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/facebook/authorize", wrapper.GetFacebookAuthUrl)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/facebook/callback", wrapper.HandleFacebookCallback)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/facebook/token/refresh", wrapper.RefreshFacebookToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/facebook/token/verify", wrapper.VerifyFacebookToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/favicon.ico", wrapper.GetFavicon)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/principals", wrapper.ListPrincipals)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/principals", wrapper.CreatePrincipal)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/principals/{principal_id}", wrapper.DeletePrincipal)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/principals/{principal_id}", wrapper.GetPrincipal)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/principals/{principal_id}", wrapper.UpdatePrincipal)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/principals/{principal_id}/posts", wrapper.DeleteAllPosts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/principals/{principal_id}/posts", wrapper.ListPosts)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/principals/{principal_id}/posts/{post_id}", wrapper.DeletePost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/principals/{principal_id}/posts/{post_id}", wrapper.GetPost)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/principals/{principal_id}/posts:batchDelete", wrapper.BatchDeletePosts)
	})

	return r
}
